#---
version: '3'
services:
  autocompound3c:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    volumes:
      - "./config.ini:/config.ini"
      - "./main.py:/main.py"
      - "./bot_config:/bot_config"
      - "./telegram:/telegram"
      - "./logs:/logs"
    command: python3 main.py
